Revert "slinky: remove unused private variable. resolves compile error on OS X: src/Target/SVMISelDAGToDAG.cpp:24:27: error: private field 'TM' is not used [-Werror,-Wunused-private-field]"
This reverts commit 36e7d9bd331eede40e7e02e5358ef6101784b147.