Revert "Revert "slinky: remove unused private variable. resolves compile error on OS X: src/Target/SVMISelDAGToDAG.cpp:24:27: error: private field 'TM' is not used [-Werror,-Wunused-private-field]""
This reverts commit b3e6203b4de13d1158578fa51af8c1c8969a6c05.