Compile error with mixed struct/class types.
cc -c -DLUA_USE_MKSTEMP -DNOT_USERSPACE -DSIFTEO_SIMULATOR
-D__STDC_FORMAT_MACROS -O3 -fomit-frame-pointer -g -MMD -Wall -Werror
-Wno-unused -Wno-strict-aliasing -Wno-uninitialized -Isrc/glfw
-Isrc/glfw/cocoa -I../deps/osx/x86_64/portaudio/include -Isrc
-I../firmware/master/common -I../firmware/master/sim
-I../firmware/include -I../sdk/include
../firmware/master/common/cube.cpp -o ../firmware/master/common/cube.o
In file included from ../firmware/master/common/cube.cpp:22:
src/system_mc.h:17:1: error: class 'SysTime' was previously declared as
a struct [-Werror,-Wmismatched-tags]
class SysTime;
^
../firmware/master/common/systime.h:15:8: note: previous use is here
struct SysTime {
       ^
src/system_mc.h:17:1: note: did you mean struct here?
class SysTime;
^~~~~
struct
src/system_mc.h:18:1: error: class 'RadioAddress' was previously
declared as a struct [-Werror,-Wmismatched-tags]
class RadioAddress;
^
../firmware/master/common/radio.h:21:8: note: previous use is here
struct RadioAddress {
       ^
src/system_mc.h:18:1: note: did you mean struct here?
class RadioAddress;
^~~~~
struct
2 errors generated.